### PR TITLE
Adding conditional logic to not attempt to resize icon if ‘convert’ c…

### PR DESCRIPTION
**Pull request by richardrauser**
…ommand is not found, i.e. ImageMagick is not installed (as in the case with vanilla MacOS)

### CODE REVIEW

**Comment by richardrauser** [comment]
Hi Boris, I thought I'd update the Makefile so that MacOS users without ImageMagick (as is the case by default) can still build this without any further action. What do you think?

**Comment by dreamlayers** [comment]
I like the idea. In fact I'm testing for it via Autoconf in another project here.

I don't like this implementation, because it basically displays garbage data and relies on the compressed full size icon being bigger than the reduced size uncompressed icon to avoid a buffer overrun. SDL won't know to decompress the PNG. The best approach would be to define a preprocessor macro, so when `convert` isn't available the icon and the code for setting it don't end up in the executable. They could also be excluded in the Emscripten build, as it seems Emscripten SDL can't set the favicon of the web page running the code.

**Comment by richardrauser** [comment]
That's a much better solution you describe. I've updated the PR so let me know what you think.

**Comment by dreamlayers** [comment]
That looks good, thanks. There's just one enhancement I'd like. Windows [has a convert.exe](https://savage.net.au/ImageMagick/html/install-convert.html). Cygwin's path by default would include that. It would be found and pass the test. How about a test which tries to see if `convert` is actually ImageMagick? I'm thinking this: `CONVERTEXISTS := $(shell command -v convert > /dev/null 2>&1 && convert -version 2> /dev/null | grep ImageMagick)`. The resulting CONVERTEXISTS will have two lines of text, but that ought to be fine, as it's just being tested using ifdef.

**Comment by dreamlayers** [comment]
Merged and then committed 7f40946 with ImageMagick test from previous comment. Tested to see it works with and without ImageMagick convert being accessible in Cygwin.

**Comment by richardrauser** [comment]
Nice, works great over here under MacOS as well. :-)

**Pull request merged**
